import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
NoteLens Obsidian Plugin
*/
`;

const prod = process.argv.includes("production");
const deploy = process.argv.includes("--deploy");
const manifest = JSON.parse(fs.readFileSync("manifest.json", "utf8"));

const rawPdfWorkerPlugin = {
	name: "notelens-pdf-worker",
	setup(build) {
		build.onResolve({ filter: /^pdfjs-dist\/build\/pdf\.worker\.min\.mjs\?raw$/ }, () => ({
			path: "pdf-worker-source",
			namespace: "notelens-pdf-worker"
		}));
		build.onLoad({ filter: /.*/, namespace: "notelens-pdf-worker" }, async () => ({
			contents: `export default ${JSON.stringify(await fs.promises.readFile(path.resolve("node_modules/pdfjs-dist/build/pdf.worker.min.mjs"), "utf8"))};`,
			loader: "js"
		}));
	}
};

function configuredPluginDir() {
	if (process.env.NOTELENS_PLUGIN_DIR?.trim()) return process.env.NOTELENS_PLUGIN_DIR.trim();
	const localConfig = "notelens.dev.json";
	if (!fs.existsSync(localConfig)) return "";
	const value = JSON.parse(fs.readFileSync(localConfig, "utf8"));
	return typeof value.pluginDir === "string" ? value.pluginDir.trim() : "";
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	define: {
		// A version stamp is deterministic, so rebuilding a release produces the same bundle.
		__NOTELENS_BUILD__: JSON.stringify(manifest.version)
	},
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	plugins: [rawPdfWorkerPlugin],
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	await context.dispose();
	console.log(`NoteLens ${manifest.version} built successfully.`);

	if (deploy) {
		const vaultPluginDir = configuredPluginDir();
		if (!vaultPluginDir) {
			throw new Error("Set NOTELENS_PLUGIN_DIR or create notelens.dev.json before running npm run deploy.");
		}
		fs.mkdirSync(vaultPluginDir, { recursive: true });
		for (const file of ["main.js", "manifest.json", "styles.css"]) {
			fs.copyFileSync(file, path.join(vaultPluginDir, file));
		}
		console.log(`Deployed to ${vaultPluginDir}`);
	}
} else {
	await context.watch();
}
