import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
NoteLens Obsidian Plugin
*/
`;

const prod = process.argv.includes("production");
const deploy = process.argv.includes("--deploy");
const manifest = JSON.parse(fs.readFileSync("manifest.json", "utf8"));

const rawPdfWorkerPlugin = {
	name: "notelens-pdf-worker",
	setup(build) {
		build.onResolve({ filter: /^pdfjs-dist\/build\/pdf\.worker\.min\.mjs\?raw$/ }, () => ({
			path: "pdf-worker-source",
			namespace: "notelens-pdf-worker"
		}));
		build.onLoad({ filter: /.*/, namespace: "notelens-pdf-worker" }, async () => ({
			contents: `export default ${JSON.stringify(await fs.promises.readFile(path.resolve("node_modules/pdfjs-dist/build/pdf.worker.min.mjs"), "utf8"))};`,
			loader: "js"
		}));
	}
};

// jsPDF's "pdfobjectnewwindow" output mode opens a window and injects PDFObject
// from a CDN. NoteLens draws its PDFs with the vector API and never asks for that
// mode, but bundling it ships the ability to fetch and run remote code, which is
// what the community review flags. The case is cut here, at build time, so the
// published main.js cannot do it at all. The var declarations stay behind: the
// next case reuses h, and var is hoisted whether or not the throw is reached.
const JSPDF_CASE = 'case"pdfobjectnewwindow":';
const JSPDF_NEXT_CASE = 'case"pdfjsnewwindow":';
const JSPDF_REPLACEMENT = JSPDF_CASE
	+ 'var a,s,u,c,l,h;'
	+ 'throw new Error("NoteLens does not bundle the pdfobjectnewwindow output of jsPDF, which loads PDFObject from a CDN.");';

let jsPdfPatched = false;
const jsPdfNoRemoteViewerPlugin = {
	name: "notelens-jspdf-no-remote-viewer",
	setup(build) {
		build.onLoad({ filter: /jspdf[\\/]dist[\\/]jspdf\.es(\.min)?\.js$/ }, async (args) => {
			const source = await fs.promises.readFile(args.path, "utf8");
			const start = source.indexOf(JSPDF_CASE);
			const end = source.indexOf(JSPDF_NEXT_CASE, start);
			if (start < 0 || end < 0) throw new Error("jsPDF changed shape: its pdfobjectnewwindow case is no longer where this patch expects it.");
			jsPdfPatched = true;
			return { contents: source.slice(0, start) + JSPDF_REPLACEMENT + source.slice(end), loader: "js" };
		});
		// A patch that silently stops matching would put the CDN loader back in the bundle.
		build.onEnd(() => {
			if (!jsPdfPatched) throw new Error("The jsPDF patch never ran: check the path it resolves to.");
		});
	}
};

function configuredPluginDir() {
	if (process.env.NOTELENS_PLUGIN_DIR?.trim()) return process.env.NOTELENS_PLUGIN_DIR.trim();
	const localConfig = "notelens.dev.json";
	if (!fs.existsSync(localConfig)) return "";
	const value = JSON.parse(fs.readFileSync(localConfig, "utf8"));
	return typeof value.pluginDir === "string" ? value.pluginDir.trim() : "";
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		// jsPDF reaches for these three with a dynamic import inside html(), which
		// NoteLens never calls: it draws the PDF with the vector API. Bundling them
		// dragged in core-js and ~880 KB of dead code, polyfills included.
		"canvg",
		"html2canvas",
		"dompurify",
		...builtins],
	define: {
		// A version stamp is deterministic, so rebuilding a release produces the same bundle.
		__NOTELENS_BUILD__: JSON.stringify(manifest.version)
	},
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	plugins: [rawPdfWorkerPlugin, jsPdfNoRemoteViewerPlugin],
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	await context.dispose();
	console.log(`NoteLens ${manifest.version} built successfully.`);

	if (deploy) {
		const vaultPluginDir = configuredPluginDir();
		if (!vaultPluginDir) {
			throw new Error("Set NOTELENS_PLUGIN_DIR or create notelens.dev.json before running npm run deploy.");
		}
		fs.mkdirSync(vaultPluginDir, { recursive: true });
		for (const file of ["main.js", "manifest.json", "styles.css"]) {
			fs.copyFileSync(file, path.join(vaultPluginDir, file));
		}
		console.log(`Deployed to ${vaultPluginDir}`);
	}
} else {
	await context.watch();
}
