import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
NoteLens Obsidian Plugin
*/
`;

const prod = (process.argv[2] === "production");

const vaultPluginDir = "C:\\Users\\jtiob\\Desktop\\Obsidian_Apuntes_Vault\\.obsidian\\plugins\\notelens";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	console.log("⚡ Build completed successfully!");

	// Copy to vault plugin directory if exists
	if (fs.existsSync(vaultPluginDir)) {
		fs.copyFileSync("main.js", path.join(vaultPluginDir, "main.js"));
		fs.copyFileSync("manifest.json", path.join(vaultPluginDir, "manifest.json"));
		fs.copyFileSync("styles.css", path.join(vaultPluginDir, "styles.css"));

		// pdf.js worker: loaded at runtime from the plugin folder
		const workerSrc = path.join("node_modules", "pdfjs-dist", "build", "pdf.worker.min.js");
		if (fs.existsSync(workerSrc)) {
			fs.copyFileSync(workerSrc, path.join(vaultPluginDir, "pdf.worker.min.js"));
			console.log("✓ pdf.js worker deployed.");
		}
		console.log("✓ Deployed directly to Obsidian Vault!");
	}
	process.exit(0);
} else {
	await context.watch();
}