import puppeteer from "puppeteer-core";
import path from "node:path";
import fs from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
const here = path.dirname(fileURLToPath(import.meta.url));
const shots = path.join(here, "shots4");
fs.mkdirSync(shots, { recursive: true });
const shot = async (page, name) => { await page.screenshot({ path: path.join(shots, name + ".png") }); console.log("shot", name); };
const sleep = (ms) => new Promise(r => setTimeout(r, ms));
const browser = await puppeteer.launch({ executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe", headless: true, args: ["--allow-file-access-from-files", "--disable-web-security", "--hide-scrollbars"], defaultViewport: { width: 1400, height: 900, deviceScaleFactor: 1 } });
const page = await browser.newPage();
const errors = [];
page.on("console", (m) => { if (m.type() === "error" || m.type() === "warning") errors.push(`[${m.type()}] ${m.text()}`); });
page.on("pageerror", (e) => errors.push(`[pageerror] ${e.message}`));
await page.goto(pathToFileURL(path.join(here, "index.html")).href, { waitUntil: "load" });
await page.waitForFunction(() => window.__ready || window.__bootError, { timeout: 20000 });
console.log("boot:", await page.evaluate(() => window.__bootError || "ok"));
const tool = async (id) => { await page.click(`.onenote-ribbon-dock [data-tool="${id}"]`); await sleep(60); };
await page.click(".notelens-insert-dock button[title='Nueva nota adhesiva']"); await sleep(100);
await page.keyboard.type("Nota adhesiva de prueba"); await page.mouse.click(1250, 820); await sleep(120);
await page.click(".notelens-insert-dock button[title='Insertar bloque de código']"); await sleep(100);
await page.keyboard.type("const x = 42;"); await page.mouse.click(1250, 820); await sleep(120);
await page.click(".notelens-insert-dock button[title='Insertar tabla']"); await sleep(120);
console.log("positions:", await page.evaluate(() => JSON.stringify([...__view.data.texts.map(t => [t.x, t.y]), ...__view.data.tables.map(t => [t.x, t.y])])));
await shot(page, "01-objects");
await tool("pen"); await sleep(50);
await shot(page, "02-pen-panel");
await tool("highlighter"); await sleep(50);
await shot(page, "03-highlighter-panel");
await tool("eraser"); await sleep(50);
await shot(page, "04-eraser-panel");
await tool("shape"); await sleep(50);
await shot(page, "05-shape-panel");
console.log("console issues:\n" + (errors.length ? errors.join("\n") : "(none)"));
await browser.close();
